spring.datasource.url= jdbc:postgresql://localhost:5432/monitoringdb
spring.datasource.username= postgres
spring.datasource.password= postgres

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update



# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info,prometheus

# Enable Prometheus endpoint
management.endpoint.prometheus.enabled=true

# Optional but recommended (for Kubernetes)
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
